name: mail_service

services:
  mail_service:
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile
    image: flashhhhh/mail_service
    environment:
      - RUNNING_ENVIRONMENT=deployment
    # ports:
    #   - 80:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=PathPrefix(`/mail`)"
      - "traefik.http.routers.mail.entrypoints=web"
      - "traefik.http.services.mail.loadbalancer.server.port=80"
      - "traefik.http.routers.mail.middlewares=mail-stripprefix"
      - "traefik.http.middlewares.mail-stripprefix.stripprefix.prefixes=/mail"
      - "traefik.docker.network=traefik_network" 
    volumes:
      - ../../deployment_logs/:/app/logs/
    networks:
      - server_administration_network
      - traefik_network

networks:
  server_administration_network:
    external: true
    name: server_administration_network
  traefik_network:
    external: true
    name: traefik_network