services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8090:8080"
    environment:
      - SWAGGER_JSON=/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml
    networks:
      - external_network
      - user_network

networks:
  external_network:
    driver: bridge
    name: external_network
  user_network:
    external: true
    name: user_network