CREATE TABLE IF NOT EXISTS servers (
    id SERIAL,
    server_id VARCHAR(255) PRIMARY KEY,
    server_name VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ipv4 VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL
);
