name: server_administration

services:
  server_administration_service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: server_administration_service
    environment:
      - RUNNING_ENVIRONMENT=deployment
    volumes:
      - ../../deployment_logs/:/app/logs/
    ports:
      - "80:80"
      - "50052:50052"
    networks:
      - server_administation_network
      - postgres_network
      - redis_network
      - elasticsearch_network
      - kafka_network

networks:
  server_administation_network:
    driver: bridge
    name: server_administration_network
  postgres_network:
    external: true
    name: postgres_network
  redis_network:
    external: true
    name: redis_network
  elasticsearch_network:
    external: true
    name: elasticsearch_network
  kafka_network:
    driver: bridge
    external: true
    name: kafka_network