name: server_administration

services:
  server_administration_service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    image: flashhhhh/server_administration_service
    environment:
      - RUNNING_ENVIRONMENT=deployment
    volumes:
      - ../../deployment_logs/:/app/logs/
    # ports:
      # - "80:80"
      # - "50052:50052"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/server`)"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.services.server.loadbalancer.server.port=80"
      - "traefik.http.routers.server.middlewares=server-stripprefix"
      - "traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/server"
      - "traefik.docker.network=traefik_network" 
    # If you don't specify which docker network traefik should use, it will forward requests in round robin fashion.
    # This will affect when your application is running in >= 2 networks.
    # So you must specify which network traefik should use.
    # Ref: https://stackoverflow.com/questions/76646646/traefik-gateway-timeout-for-service-with-multiple-networks
    networks:
      - server_administration_network
      - postgres_network
      - redis_network
      - elasticsearch_network
      - kafka_network
      - traefik_network

networks:
  server_administration_network:
    driver: bridge
    name: server_administration_network
  postgres_network:
    external: true
    name: postgres_network
  redis_network:
    external: true
    name: redis_network
  elasticsearch_network:
    external: true
    name: elasticsearch_network
  kafka_network:
    external: true
    name: kafka_network
  traefik_network:
    external: true
    name: traefik_network