name: user_service

services:
  user_service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    image: flashhhhh/user_service
    environment:
      - RUNNING_ENVIRONMENT=deployment
    volumes:
      - ../../deployment_logs/:/app/logs/
    # ports:
      # - "80:80"
      # - "50051:50051"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/user`)"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.services.user.loadbalancer.server.port=80"
      - "traefik.http.routers.user.middlewares=user-stripprefix"
      - "traefik.http.middlewares.user-stripprefix.stripprefix.prefixes=/user"
      - "traefik.docker.network=traefik_network"
    networks:
      - traefik_network
      - postgres_network

networks:
  postgres_network:
    external: true
    name: postgres_network
  traefik_network:
    external: true
    name: traefik_network