name: user_service

services:
  user_service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    image: flashhhhh/user_service
    environment:
      - RUNNING_ENVIRONMENT=deployment
    volumes:
      - ../../deployment_logs/:/app/logs/
    ports:
      - "80:80"
      - "50051:50051"
    networks:
      - postgres_network

networks:
  postgres_network:
    external: true
    name: postgres_network