openapi: 3.1.0
info:
  title: User Service API
  description: API for managing users
  version: 1.0.0
servers:
  - url: http://localhost:10001
    description: Local user server
  - url: http://localhost:10002
    description: Local server administration server
  
  - url: http://localhost:80
    description: Deployment server
paths:
  /user/create:
    post:
      summary: Create a new user
      description: Creates a new user with the provided details.
      requestBody:
        description: User information
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: abc123@gmail.com
                role:
                  type: string
                  enum: [sudo, admin, user]
                  example: user
              required:
                - username
                - password
                - name
                - role
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  userID:
                    type: string
                    example: 12345
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /user/login:
    post:
      summary: User login
      description: Authenticates a user and returns a token.
      requestBody:
        description: User login credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: abcdef1234567890
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid username or password
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /user/getUserByID:
    get:
      summary: Get user by ID
      description: Retrieves user information based on the provided user ID.
      parameters:
        - name: userID
          in: query
          required: true
          description: The ID of the user to retrieve
          schema:
            type: string
            example: 12345
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                    example: 12345
                  username:
                    type: string
                    example: johndoe
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    format: email
                    example:
                  role:
                    type: string
                    enum: [sudo, admin, user]
                    example: user
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /user/getAllUsers:
    get:
      summary: Get all users
      description: Retrieves a list of all users.
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userID:
                      type: string
                      example: 12345
                    username:
                      type: string
                      example: johndoe
                    name:
                      type: string
                      example: John Doe
                    email:
                      type: string
                      format: email
                      example:
                    role:
                      type: string
                      enum: [sudo, admin, user]
                      example: user
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /server/create:
    post:
      summary: Create a new server
      description: Creates a new server with the provided details.
      requestBody:
        description: Server information
        content:
          application/json:
            schema:
              type: object
              properties:
                server_id:
                  type: string
                  example: "1"
                server_name:
                  type: string
                  example: "Server 1"
                status:
                  type: string
                  example: "On"
                ipv4:
                  type: string
                  format: ipv4
                  example: ""
                port:
                  type: int
                  example: 80
              required:
                - server_id
                - server_name
                - status
                - ipv4

      responses:
        '201':
          description: Server created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server created successfully
                  serverID:
                    type: string
                    example: 12345
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
  /server/update:
    put:
      summary: Update server information
      description: Updates the information of an existing server.
      parameters:
        - name: server_id
          in: query
          required: true
          description: The ID of the server to update
          schema:
            type: string
            example: "1"
      requestBody:
        description: Updated server information
        content:
          application/json:
            schema:
              type: object
              properties:
                server_name:
                  type: string
                  example: "Updated Server 1"
                status:
                  type: string
                  example: "Off"
                ipv4:
                  type: string
                  format: ipv4
                  example: ""
                port:
                  type: int
                  example: 8080
      responses:
        '200':
          description: Server updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server updated successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /server/delete:
    delete:
      summary: Delete a server
      description: Deletes a server with the provided ID.
      parameters:
        - name: server_id
          in: query
          required: true
          description: The ID of the server to delete
          schema:
            type: string
            example: "1"
      responses:
          '200':
            description: Server deleted successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Server deleted successfully
          '400': 
            description: Bad request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Invalid server ID
          '404':
            description: Server not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Server not found
          '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Internal server error
  /server/import:
    post:
      summary: Import server data
      description: Imports server data from a file.
      requestBody:
        description: File containing server data
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                servers_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Server data imported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server data imported successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid file format
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error